// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5OTjLIzW59glxE_q7bLiWG06OGRfWJq4',
    appId: '1:50634132035:web:90641a1d66c116a2b4a2f6',
    messagingSenderId: '50634132035',
    projectId: 'concious-living-app',
    authDomain: 'concious-living-app.firebaseapp.com',
    storageBucket: 'concious-living-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2o6X7jzVPdJIgChkIAVyNMqcxbFt1vA',
    appId: '1:50634132035:android:906e9bc4713d9f8eb4a2f6',
    messagingSenderId: '50634132035',
    projectId: 'concious-living-app',
    storageBucket: 'concious-living-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUYSpux71A1bULmPWIxrF5VbB8bCcXXA',
    appId: '1:50634132035:ios:ad08fc9a7a779a30b4a2f6',
    messagingSenderId: '50634132035',
    projectId: 'concious-living-app',
    storageBucket: 'concious-living-app.firebasestorage.app',
    iosBundleId: 'com.example.conciousLivingApp',
  );
}
